name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Create signing config
      run: |
        echo ${{ secrets.SIGNINGKEYBASE64 }} | base64 --decode > keystore.jks
        echo RELEASE_STORE_FILE=../keystore.jks > keystore.properties
        echo RELEASE_STORE_PASSWORD=${{ secrets.KEYSTOREPASSWORD }} >> keystore.properties
        echo RELEASE_KEY_ALIAS=${{ secrets.ALIAS }} >> keystore.properties
        echo RELEASE_KEY_PASSWORD=${{ secrets.KEYPASSWORD }} >> keystore.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Rename release APK
      run: |
        mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/ThermalDetector.apk

    - uses: actions/upload-artifact@v4
      with:
        name: signed-apk
        if-no-files-found: error
        path: app/build/outputs/apk/release


  release:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - run: mkdir -p app/build/release
    - uses: actions/download-artifact@v4
      with:
        name: signed-apk
        path: app/build/release

    - name: Get version time  
      uses: 1466587594/get-current-time@v2    
      id: version-name    
      with:
        format: "YYYY.MMDD.HHmm"

    - name: Create release
      id: create_release_id
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v_${{ steps.version-name.outputs.formattedTime }}
        release_name: Release ${{ steps.version-name.outputs.formattedTime }}

    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_id.outputs.upload_url }}
        asset_path: app/build/release/ThermalDetector.apk
        asset_name: ThermalDetector.apk
        asset_content_type: application/vnd.android.package-archive